# spring:
#   application:
#     name: backend
#   # 默认激活 dev 配置（可按需修改或在运行时覆盖）
#   profiles:
#     active: dev

spring:
  profiles:
    active: dev # 👈 激活开发环境

app:
  jwt:
    secret: "minitiktok_dev_secret_key_should_be_at_least_32_chars"
    expire-seconds: 7200
    issuer: "little-tiktok"
